#include <furi.h>
#include <stdio.h>
#include <gui/gui.h>

/* generated by fbt from .png files in images folder */
#include <flippybird_icons.h>

static void draw_callback(Canvas* canvas, void* ctx) {
    UNUSED(ctx);

    canvas_clear(canvas);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 32, 13, "Hello, World!");

    canvas_set_font(canvas, FontSecondary);
    canvas_draw_str(canvas, 15, 40, "press back to exit the FAP!");
    canvas_draw_line(canvas, 2, 23, 126, 23);
}

static void input_callback(InputEvent* ie, void* ctx) {
    furi_assert(ctx);
    FuriMessageQueue* event_queue = ctx;
    furi_message_queue_put(event_queue, ie, FuriWaitForever);
}

int32_t flippybird_main(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm flippybird!");

    InputEvent event;
    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(InputEvent));

    ViewPort* viewport = view_port_alloc();
    view_port_draw_callback_set(viewport, draw_callback, NULL);
    view_port_input_callback_set(viewport, input_callback, event_queue);

    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, viewport, GuiLayerFullscreen);

    for(;;) {
        furi_check(furi_message_queue_get(event_queue, &event, FuriWaitForever) == FuriStatusOk);

        // exit when the back key is pressed
        if(event.key == InputKeyBack) {
            break;
        }
    }

    //free memory
    furi_message_queue_free(event_queue);
    gui_remove_view_port(gui, viewport);
    view_port_free(viewport);
    furi_record_close(RECORD_GUI);

    return 0;
}
